language: objective-c
osx_image: xcode9.1
script:
  - xcodebuild -scheme LocalizedString -workspace LocalizedString.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=9.1' build test
after_success:


